version: "3.7"

volumes:
  matchvolume:
    name: match-volume

networks:
  matchnetwork:
    name: matcher-network

services:
  pg:
    image: postgres:12.0
    restart: on-failure
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - matchvolume:/var/lib/postgresql/data
      - ./db/scripts:/docker-entrypoint-initdb.d/
    networks:
      - matchnetwork 
  match_api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - pg
    volumes:
      - ./:/app
    ports:
      - 3001:3001
    networks:
      - matchnetwork
    env_file:
      - .env